### ISSUE TITLE
[Bug]: Custom notification can't be set - typo in manual

### ISSUE THREAD

**Issue by BenKruft** [TappNetwork/Filament-Invite#4]
### What happened?

In the manual: "implement the sendPassword**Reset**Notification method on the user model". 
In your code: if (method_exists($user, 'sendPassword**Set**Notification')) {

### How to reproduce the bug

Follow the manual and try to add a custom notification

### Package Version

1.0.0

### PHP Version

8.2.0

### Laravel Version

10.0

**Comment by scottgrayson** [comment]
I've updated the method_exists check to match the name in the readme @BenKruft 

Thanks for the report!

**Comment by BenKruft** [comment]
Thanks for the quick reply. I thought you'll change the manual but this is also good or maybe better. 
There is one more problem, the line after the method_exists needs an update to: 

`if (method_exists($user, 'sendPasswordResetNotification')) {
  $user->sendPasswordSetNotification($token);`

**Comment by scottgrayson** [comment]
Updated.

Thank you
